### PR TITLE
typo: "thing" to "think"

### PR DESCRIPTION
**Pull request by ajschumacher**

### CODE REVIEW

**Comment by tlevine** [comment]
Thanks, I merged it

**Comment by ajschumacher** [comment]
Cool! Do you want to close the PR then?

**Comment by tlevine** [comment]
I don't care. Or do I? Here are directions in case that seems
important later.
https://help.github.com/articles/closing-a-pull-request/

**Comment by ajschumacher** [comment]
Doesn't matter much! I'm going to close it so it doesn't show up when I check my open pull requests.

**Pull request closed without merging**
